/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package weatherstation;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author oskar
 */
public class GUI extends javax.swing.JFrame {

    private BL bl = new BL();
    public GUI() {
        initComponents();
        
        tableWeather.setModel(bl);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableWeather = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btAddWeatherSt = new javax.swing.JMenuItem();
        btRemoveWetherSt = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btSetTemp = new javax.swing.JMenuItem();
        btSetHumidity = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableWeather.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableWeather);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Stations");

        btAddWeatherSt.setText("Add Weather Station");
        btAddWeatherSt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddWeatherStActionPerformed(evt);
            }
        });
        jMenu1.add(btAddWeatherSt);

        btRemoveWetherSt.setText("remove Weather Station");
        btRemoveWetherSt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveWetherStActionPerformed(evt);
            }
        });
        jMenu1.add(btRemoveWetherSt);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Values");

        btSetTemp.setText("Set Tempreture");
        btSetTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSetTempActionPerformed(evt);
            }
        });
        jMenu2.add(btSetTemp);

        btSetHumidity.setText("Set  Humiidity");
        btSetHumidity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSetHumidityActionPerformed(evt);
            }
        });
        jMenu2.add(btSetHumidity);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddWeatherStActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddWeatherStActionPerformed
        DialogWetterStation d = new DialogWetterStation(this, true);
        d.setVisible(true);
        if(d.isOk()){
            bl.add(d.getW());
        }
    }//GEN-LAST:event_btAddWeatherStActionPerformed

    private void btRemoveWetherStActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveWetherStActionPerformed
        bl.remove(tableWeather.getSelectedRows());
    }//GEN-LAST:event_btRemoveWetherStActionPerformed

    private void btSetTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSetTempActionPerformed
        try {
            bl.setTemp(tableWeather.getSelectedRow(),Double.parseDouble(JOptionPane.showInputDialog(null,"Please enter a Tempreture")));
        } catch (Exception ex) {
    System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btSetTempActionPerformed

    private void btSetHumidityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSetHumidityActionPerformed
        try {
            bl.setHumidity(tableWeather.getSelectedRow(),Integer.parseInt(JOptionPane.showInputDialog(null,"Please enter the Humidity")));
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btSetHumidityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btAddWeatherSt;
    private javax.swing.JMenuItem btRemoveWetherSt;
    private javax.swing.JMenuItem btSetHumidity;
    private javax.swing.JMenuItem btSetTemp;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableWeather;
    // End of variables declaration//GEN-END:variables
}
